require('./models/init')
require('./services/init')
// require('./test/area.test')
// require('./test/vendor.test')
// require('./test/position.test')
// require('./test/email.test')
// require('./test/user.test')
// require('./test/complain.test')
// require('./test/stall.test')
require('./test/apply.test')